#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing, and building your project before committing'

# Check Prettier standards
bun run check-format ||
(
    echo '⚠️ Please check your code formatting.
            Prettier check failed. Run bun run format, add the changes, and try committing again.';
    false;
)

# Check ESLint Standards
bun run check-lint ||
(
    echo '⚠️ Please address the linting issues.
            ESLint check failed. Make the required changes listed above, add the changes, and try committing again.'
    false; 
)

# Check tsconfig standards
bun run check-types ||
(
    echo '⚠️ Type check failed.
            Please review and fix the type errors listed above.'
    false;
)

# If everything passes... Now we can commit
echo '✅ All checks passed. Building the project now.'

bun run build ||
(
    echo '❌ Build failed.
            Please review the errors above and try to resolve them.'
    false;
)

# If everything passes... Now we can commit
echo '✅ All checks and build succeeded. Committing your changes now.'
